name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read

env:
  ImageOS: "ubuntu20"
  MIX_ENV: "test"
  OTP_VERSION_SPEC: "25.2"
  ELIXIR_VERSION_SPEC: "1.14.3"
  NIXPKGS_ALLOW_UNFREE: "1"

jobs:
  unit-tests:
    name: Build and unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install dependencies
        run: nix-shell --run "mix deps.get"
      - name: Run tests
        run: nix-shell --run "mix test --exclude integration:true"

  integration-tests:
    name: Build and integration test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install dependencies
        run: nix-shell --run "mix deps.get"
      - name: Starts In-Memory Surreal DB
        run: nix-shell --run "surreal start --log trace --user root --pass root memory &"
      - name: Run tests
        run: nix-shell --run "mix test --only integration:true"
